import type { BasicTeacherStep } from "./types";

/** 原文：Lockhart, The Basic Teacher (1950) · zbenglish.net/sites/basic/bt0.html */
export const BASIC_TEACHER_STEPS: BasicTeacherStep[] = [
  {
    id: "bt1",
    number: 1,
    title: "Step 1 · Structure",
    titleZh: "名词、形容词、方位",
    source: "Lockhart · The Basic Teacher (1950)",
    kind: "structure",
    vocab: ["bed", "building", "door", "flower", "house", "pot", "room", "table", "window", "round", "wide", "narrow", "put", "take", "in", "on", "off", "between", "by", "against", "over", "under"],
    structureSentences: [
      "This is a building.",
      "This is my room.",
      "My room is in that house.",
      "The room is narrow. The window is wide.",
      "I put the pot on the table.",
      "I take the pot off the table.",
      "The bed is against the door.",
      "The table is between the door and the window.",
      "The pot is on the table.",
      "This room is over my room. My room is under this room.",
      "A bed and a table are in the room.",
    ],
    fillBlanks: [
      {
        id: "bt1-f1",
        template: "The windows in this room ___ round.",
        blanks: ["are"],
      },
      {
        id: "bt1-f2",
        template: "This is ___ room in my house.",
        blanks: ["a"],
      },
      {
        id: "bt1-f3",
        template: "Pots ___ on the table.",
        blanks: ["are"],
      },
      {
        id: "bt1-f4",
        template: "I take ___ pot off the table.",
        blanks: ["the"],
      },
      {
        id: "bt1-f5",
        template: "That is my flower. The flower ___ in a pot.",
        blanks: ["is"],
      },
    ],
    questions: [
      { id: "bt1-q1", prompt: "Name the opposite of: narrow", answers: ["Wide.", "wide"] },
      { id: "bt1-q2", prompt: "Name the opposite of: put", answers: ["Take.", "take"] },
      { id: "bt1-q3", prompt: "Name the opposite of: off", answers: ["On.", "on"] },
      { id: "bt1-q4", prompt: "Change into plural: This narrow bed is between the windows.", answers: ["These narrow beds are between the windows.", "these narrow beds are between the windows"] },
    ],
  },
  {
    id: "bt2",
    number: 2,
    title: "Step 2 · My Room",
    titleZh: "阅读：我的房间",
    source: "Lockhart · The Basic Teacher (1950)",
    kind: "reading",
    vocab: ["book", "cover", "curtain", "cushion", "drawer", "floor", "frame", "picture", "seat", "wall", "black", "white"],
    readingTitle: "My Room",
    readingParagraphs: [
      "This building is a house. It is a white house. My room is in this white house. This is my room.",
      "My bed is against this wall. It is under the wide window. My books are on that narrow black table between the bed and the door.",
      "A picture in a frame is on the wall over the books. The walls are white and the floor is black.",
      "I take the white flower off the floor and put it in the pot. I take a book off that table and put it in the drawer.",
    ],
    questions: [
      { id: "bt2-q1", prompt: "Which table are the seats by?", answers: ["The round table.", "the round table", "By the round table."] },
      { id: "bt2-q2", prompt: "Where is the white flower?", answers: ["On the floor under the table.", "on the floor under the table", "Under the table."] },
      { id: "bt2-q3", prompt: "What color are the curtains?", answers: ["Black.", "black", "The curtains are black."] },
      { id: "bt2-q4", prompt: "What do you do with the cover on your bed?", answers: ["I take the cover off my bed and put it on a seat.", "take the cover off my bed"] },
      { id: "bt2-q5", prompt: "Describe the pot on the table.", answers: ["The pot is round and black.", "the pot is round and black", "It is round and black."] },
    ],
  },
  {
    id: "bt3",
    number: 3,
    title: "Step 3 · Structure",
    titleZh: "come/go · give/get",
    source: "Lockhart · The Basic Teacher (1950)",
    kind: "structure",
    vocab: ["arm", "box", "hand", "man", "office", "pocket", "shelf", "ticket", "come", "go", "give", "get", "to", "from", "with", "at", "across"],
    structureSentences: [
      "I give a book to the woman.",
      "She gets it from me and gives it to the man.",
      "He comes from this office to her house.",
      "He and she come to my room.",
      "I go to my house and he goes to his house.",
      "I take the tickets to my office.",
      "The man is at the house. She is at the door.",
      "This is not a shelf. The ticket is not in his hand.",
    ],
    fillBlanks: [
      { id: "bt3-f1", template: "I give a book ___ my friend.", blanks: ["to"] },
      { id: "bt3-f2", template: "She goes ___ me.", blanks: ["with"] },
      { id: "bt3-f3", template: "This side ___ the ticket is white.", blanks: ["of"] },
      { id: "bt3-f4", template: "I put the ticket ___ my pocket.", blanks: ["in"] },
    ],
    questions: [
      { id: "bt3-q1", prompt: "Turn into negative: This is the hand of a man.", answers: ["This is not the hand of a man.", "this is not the hand of a man"] },
      { id: "bt3-q2", prompt: "Turn into negative: I am at the door of the office.", answers: ["I am not at the door of the office.", "i am not at the door of the office"] },
    ],
  },
  {
    id: "bt4",
    number: 4,
    title: "Step 4 · At the Station",
    titleZh: "阅读：在车站",
    source: "Lockhart · The Basic Teacher (1950)",
    kind: "reading",
    vocab: ["station", "train", "ticket", "porter", "bag", "friend", "road", "street", "store", "flag", "quick", "slow", "frequent"],
    readingTitle: "At the Station",
    readingParagraphs: [
      "That is the road to the station. My house is in this street. It is not by the station.",
      "I go to my office in a train. I am with a friend. He goes with me to the station.",
      "At the station I get tickets. I give a ticket to my friend and put the other in my pocket.",
      "Here is my train. The back of the train is full. The front of the train is not full.",
      "I give the seat by the window to my friend. The porter gives the bag to me and I put it across the seat between me and my friend.",
    ],
    questions: [
      { id: "bt4-q1", prompt: "Who goes with you to the station?", answers: ["A friend.", "a friend", "My friend.", "my friend"] },
      { id: "bt4-q2", prompt: "Which part of the train is full?", answers: ["The back of the train.", "the back of the train", "The back.", "the back"] },
      { id: "bt4-q3", prompt: "What is under the woman's arm?", answers: ["A bag and a cushion.", "a bag and a cushion", "bag and cushion"] },
      { id: "bt4-q4", prompt: "How do you go to the office?", answers: ["In a train.", "in a train", "By train.", "I go in a train."] },
      { id: "bt4-q5", prompt: "Is your train a quick one or a slow one?", answers: ["A quick train.", "a quick train", "Quick.", "quick", "It is a quick train."] },
    ],
  },
];
