import type { StepByStepLesson } from "./types";

/** 原文：Ogden, Basic Step by Step (1935) · zbenglish.net/sites/basic/bsbs.html */
export const STEP_BY_STEP_LESSONS: StepByStepLesson[] = [
  {
    id: "body",
    number: 1,
    title: "The Body",
    titleZh: "身体",
    source: "Ogden · Basic Step by Step (1935)",
    vocab: ["arm", "body", "chest", "chin", "ear", "eye", "face", "finger", "hand", "head", "knee", "leg", "mouth", "nose", "thumb", "tongue", "front", "back", "right", "left", "straight", "bent"],
    modelSentences: [
      "This is my body.",
      "This is my head.",
      "This is my face.",
      "I have a nose and a chin.",
      "My mouth is between my nose and my chin.",
      "I have a tongue in my mouth.",
      "This part is the front. That part is the back.",
      "This is the right side. The opposite side is the left side.",
      "I put my right hand on my head.",
      "I take my right hand off my head.",
      "This finger is bent. That finger is straight.",
    ],
    questions: [
      { id: "b1", prompt: "What is between your nose and your chin?", answers: ["My mouth.", "my mouth"] },
      { id: "b2", prompt: "Where is your tongue?", answers: ["In my mouth.", "in my mouth"] },
      { id: "b3", prompt: "What have you on your hand?", answers: ["A thumb and fingers.", "a thumb and fingers"] },
      { id: "b4", prompt: "What is the opposite of straight?", answers: ["Bent.", "bent"] },
      { id: "b5", prompt: "Where is your right ear?", answers: ["At the right side.", "at the right side", "My right ear is at the right side."] },
    ],
  },
  {
    id: "food",
    number: 2,
    title: "Food",
    titleZh: "食物",
    source: "Ogden · Basic Step by Step (1935)",
    vocab: ["bread", "butter", "cake", "cheese", "food", "meat", "orange", "salt", "sugar", "basin", "fork", "knife", "meal", "plate", "spoon", "table", "sweet", "bitter", "acid"],
    modelSentences: [
      "Some food is on the table.",
      "A meal is ready.",
      "I take my spoon in my hand and put the soup in my mouth.",
      "I put salt on my meat.",
      "I take butter on my knife and put it on my bread.",
      "I will take the skin off the orange.",
      "The taste of sugar is sweet.",
      "This cake is sweet and sticky.",
    ],
    questions: [
      { id: "f1", prompt: "What do you have at a meal?", answers: ["Food.", "food"] },
      { id: "f2", prompt: "Where do you have it?", answers: ["At the table.", "at the table"] },
      { id: "f3", prompt: "What do you put on your meat?", answers: ["Salt.", "salt"] },
      { id: "f4", prompt: "What do you do to an orange before you give it a bite?", answers: ["I take the skin off.", "I take the skin off the orange.", "take the skin off"] },
      { id: "f5", prompt: "What foods named here have a sweet taste?", answers: ["Sugar and cake.", "sugar and cake"] },
    ],
  },
  {
    id: "work",
    number: 3,
    title: "Work",
    titleZh: "工作",
    source: "Ogden · Basic Step by Step (1935)",
    vocab: ["learning", "work", "rest", "play", "brain", "cloth", "coat", "needle", "thread", "scissors", "stitch", "button", "sharp", "tired"],
    modelSentences: [
      "The learning of Basic English is a sort of work.",
      "I do it with my brain.",
      "My scissors are sharp.",
      "I put the thread through the hole in the needle.",
      "I make a stitch.",
      "I put a button on the coat.",
      "The coat is ready.",
      "After work my body is tired, and I have some rest.",
    ],
    questions: [
      { id: "w1", prompt: "What work are you doing now?", answers: ["Learning Basic English.", "The learning of Basic English.", "learning Basic English"] },
      { id: "w2", prompt: "What part of your body is used for this work?", answers: ["My brain.", "my brain"] },
      { id: "w3", prompt: "How do you get the cloth cut?", answers: ["With scissors.", "with scissors"] },
      { id: "w4", prompt: "What do you do when your body is tired?", answers: ["I have some rest.", "I have rest.", "have some rest"] },
      { id: "w5", prompt: "What will you do when you have had a rest?", answers: ["I will have some play.", "have some play"] },
    ],
  },
  {
    id: "weather",
    number: 4,
    title: "The Weather",
    titleZh: "天气",
    source: "Ogden · Basic Step by Step (1935)",
    vocab: ["air", "cloud", "ice", "rain", "sky", "snow", "summer", "winter", "wind", "umbrella", "warm", "cold", "wet", "dry", "clear"],
    modelSentences: [
      "The weather is warm in the summer, but in the winter it is cold.",
      "Rain is wet. It is water from the sky.",
      "Rain and snow do not come from a clear sky.",
      "In wet weather I get an umbrella and put it over my head.",
      "In the winter I see the breath from my mouth in the air.",
      "I take a mass of snow in my hands and make a ball.",
    ],
    questions: [
      { id: "we1", prompt: "When is the weather cold, and when is it warm?", answers: ["It is cold in the winter and warm in the summer.", "cold in the winter and warm in the summer"] },
      { id: "we2", prompt: "What may come from the sky in cold weather or in warm weather?", answers: ["Rain.", "rain"] },
      { id: "we3", prompt: "What will keep you dry in the rain?", answers: ["An umbrella.", "an umbrella"] },
      { id: "we4", prompt: "In England what winds are very cold winds?", answers: ["North and east winds.", "north and east winds"] },
      { id: "we5", prompt: "What winds are warm winds?", answers: ["South and west winds.", "south and west winds"] },
    ],
  },
  {
    id: "family",
    number: 5,
    title: "The Family",
    titleZh: "家庭",
    source: "Ogden · Basic Step by Step (1935)",
    vocab: ["father", "mother", "son", "daughter", "brother", "sister", "baby", "boy", "girl", "man", "woman", "family", "healthy", "ill", "young", "old"],
    modelSentences: [
      "My father is a young man and my mother is a young woman.",
      "I have one sister and one brother.",
      "My brother is very young. He is still a baby.",
      "I will get some milk for my baby brother.",
      "A kiss and a smile make a baby ready for play.",
      "The brothers and sisters of my mother and father are men and women.",
    ],
    questions: [
      { id: "fa1", prompt: "What is a boy to his father and mother?", answers: ["A son.", "a son"] },
      { id: "fa2", prompt: "What is a girl to her father and mother?", answers: ["A daughter.", "a daughter"] },
      { id: "fa3", prompt: "What do very young babies not have?", answers: ["Teeth.", "teeth"] },
      { id: "fa4", prompt: "What will the boy get for the baby?", answers: ["Some milk.", "some milk", "Milk.", "milk"] },
      { id: "fa5", prompt: "What will make a baby ready for play?", answers: ["A kiss and a smile.", "a kiss and a smile"] },
    ],
  },
  {
    id: "building",
    number: 6,
    title: "A Building",
    titleZh: "建筑",
    source: "Ogden · Basic Step by Step (1935)",
    vocab: ["building", "house", "room", "door", "floor", "wall", "window", "roof", "street", "high", "low", "wide", "narrow"],
    modelSentences: [
      "This building is a house.",
      "My room is in this house.",
      "The door is in the wall.",
      "The window is wide.",
      "The floor is under my feet.",
      "The roof is over the room.",
    ],
    questions: [
      { id: "bu1", prompt: "What is a building?", answers: ["A sort of structure.", "a sort of structure", "A structure."] },
      { id: "bu2", prompt: "Where is the floor?", answers: ["Under my feet.", "under my feet", "Under the room.", "under the room"] },
      { id: "bu3", prompt: "What is over the room?", answers: ["The roof.", "the roof"] },
      { id: "bu4", prompt: "What is the opposite of wide?", answers: ["Narrow.", "narrow"] },
      { id: "bu5", prompt: "Name five parts of a house.", answers: ["Door, floor, wall, window, roof.", "door floor wall window roof"] },
    ],
  },
];
