import json, re

# 462句中文翻译
ZH_462 = {
    "Have no fear.": "不要害怕。",
    "Make a journey to the north.": "去北方旅行。",
    "Let us have it out.": "我们来把话说清楚。",
    "She saw the boy off to school.": "她送男孩去上学。",
    "I give orders here.": "我在这里发号施令。",
    "They gave us an offer.": "他们给了我们一个提议。",
    "The lamp gives off light.": "灯发出光。",
    "She gave out the papers.": "她分发了文件。",
    "He made off quickly.": "他迅速离开了。",
    "I get up every morning.": "我每天早上起床。",
    "They gave in to the force.": "他们屈服于武力。",
    "Do your writing before you go.": "在你走之前把写作做完。",
    "I made a move to the door.": "我向门口走去。",
    "We do business together.": "我们一起做生意。",
    "I will make use of this.": "我会利用这个。",
    "They saw the ship off.": "他们送别了船。",
    "They did up the old house.": "他们翻新了老房子。",
    "They went through the town.": "他们穿过了城镇。",
    "She had the argument out.": "她把争论说清楚了。",
    "The flower gives off a sweet smell.": "花散发出甜美的气味。",
    "They got out of the house.": "他们从房子里出来了。",
    "They did the business well.": "他们把生意做得很好。",
    "Keep up the good work.": "保持良好的工作。",
    "He made for the river.": "他朝河边走去。",
    "She has a look at the picture.": "她看了看那幅画。",
    "She made a great discovery.": "她有了一个伟大的发现。",
    "I cannot do with this noise.": "我受不了这噪音。",
    "Do not give up.": "不要放弃。",
    "Go over the road.": "过马路。",
    "The train came in.": "火车进站了。",
    "He could do with a rest.": "他需要休息一下。",
    "She gives a push to the box.": "她推了一下箱子。",
    "See to the door.": "处理一下门的事。",
    "I can do without it.": "我没有它也行。",
    "She has a strong belief.": "她有强烈的信念。",
    "He went without help.": "他没有寻求帮助就去了。",
    "They saw through the plan.": "他们看穿了这个计划。",
    "She could do with some help.": "她需要一些帮助。",
    "I gave up smoking.": "我戒烟了。",
    "I made up the loss.": "我弥补了损失。",
    "They gave back the land.": "他们归还了土地。",
    "Make a comparison between the two.": "在两者之间做个比较。",
    "They got over the river.": "他们过了河。",
    "I keep off the street at night.": "我晚上不去街上。",
    "She does good writing.": "她写得好。",
    "They made the request together.": "他们一起提出了请求。",
    "I make a start on the work.": "我开始做这项工作。",
    "Get over it.": "克服它。",
    "He made the right decision.": "他做了正确的决定。",
    "The sun came up.": "太阳升起来了。",
    "Keep your hands off.": "不要碰。",
    "This had an effect on me.": "这对我有影响。",
    "They gave the order to stop.": "他们下了停止的命令。",
    "He keeps off drink.": "他不喝酒。",
    "The secret got out.": "秘密泄露了。",
    "She made a comparison.": "她做了一个比较。",
    "Get off the table.": "从桌子上下来。",
    "She did the letter over.": "她重写了信。",
    "I will make a comparison.": "我会做个比较。",
    "Make up the fire.": "把火生起来。",
    "She came out to see me.": "她出来看我。",
    "He came through a hard time.": "他经历了一段艰难的时光。",
    "They made off before I saw them.": "他们在我看到之前就跑了。",
    "I had friends in.": "我请了朋友来家里。",
    "I have on a coat.": "我穿着外套。",
    "Make your move.": "行动吧。",
    "I will make an attempt.": "我会尝试一下。",
    "Keep the heat in.": "保持热量。",
    "Have the cat in.": "把猫放进来。",
    "They kept the water off.": "他们挡住了水。",
    "Come down from the seat.": "从座位上下来。",
    "They have deep knowledge.": "他们有深厚的知识。",
    "The light came through the window.": "光线从窗户照进来。",
    "He had a strange feeling.": "他有一种奇怪的感觉。",
    "I give up.": "我放弃。",
    "He did up the room.": "他整理了房间。",
    "He came back with the key.": "他带着钥匙回来了。",
    "Do not give in to fear.": "不要向恐惧屈服。",
    "He gave up hope.": "他放弃了希望。",
    "Come in from the rain.": "从雨里进来。",
    "Keep down the noise.": "降低噪音。",
    "He had a fear of the dark.": "他害怕黑暗。",
    "Come across the bridge.": "过桥。",
    "Come down and help me.": "下来帮我。",
    "Get out of the way.": "让开。",
    "He makes a request every day.": "他每天都提出请求。",
    "I got out of the train.": "我下了火车。",
    "Make for the door.": "朝门口走去。",
    "He came out of the water.": "他从水里出来了。",
    "We went to see her off.": "我们去送别她。",
    "Do no harm.": "不要伤害。",
    "She gave in at last.": "她最终屈服了。",
    "I have a fear of fire.": "我害怕火。",
    "I got back to work.": "我回去工作了。",
    "Do not do harm to yourself.": "不要伤害自己。",
    "Come back to the house.": "回到房子。",
    "I got in the room.": "我进了房间。",
    "Do your reading now.": "现在做你的阅读。",
    "Go back and get the key.": "回去拿钥匙。",
    "What do you do with this?": "你用这个做什么？",
    "I will make a start tomorrow.": "我明天开始。",
    "I do business in the town.": "我在城里做生意。",
    "I went over the bridge.": "我过了桥。",
    "Get in the train.": "上火车。",
    "He had a desire to go.": "他渴望去。",
    "He goes back every year.": "他每年都回去。",
    "I do my writing in the morning.": "我早上做写作。",
    "She kept the price down.": "她压低了价格。",
    "Send back an answer.": "发回一个答案。",
    "Keep the secret in.": "保守秘密。",
    "Do not let me down.": "不要让我失望。",
    "I have belief in the future.": "我对未来有信心。",
    "I did up the parcel.": "我包扎好了包裹。",
    "Go with the boy.": "和男孩一起去。",
    "They got on together.": "他们相处得很好。",
    "I got through the book.": "我看完了这本书。",
    "Keep the dog in.": "把狗关在屋里。",
    "Come through the door.": "从门进来。",
    "She made off into the night.": "她在夜里溜走了。",
    "I make use of the library.": "我利用这个图书馆。",
    "I did the room over.": "我重新整理了房间。",
    "I got off work early.": "我很早就下班了。",
    "Get up and go to the door.": "起来，走到门口。",
    "They cannot do without water.": "他们离不开水。",
    "Come across the street.": "横穿马路。",
    "Do the work over.": "把工作重做一遍。",
    "She gave help to the old man.": "她帮助了老人。",
    "They let the prisoner out.": "他们释放了囚犯。",
    "The rain came down.": "雨落了下来。",
    "Let the air out.": "放出空气。",
    "I will do the work tomorrow.": "我明天做这个工作。",
    "I have love for my family.": "我热爱我的家庭。",
    "She let off the gun.": "她开了枪。",
    "I cannot make out the writing.": "我看不清字迹。",
    "Let the window down.": "把窗户放下来。",
    "Have it out with him.": "和他把话说清楚。",
    "He makes use of every chance.": "他利用每一个机会。",
    "I got up the steps.": "我走上了台阶。",
    "He got in late.": "他很晚才到。",
    "She let out the secret.": "她泄露了秘密。",
    "He came across a strange thing.": "他遇到了一件奇怪的事。",
    "He did the reading quickly.": "他很快做了阅读。",
    "Go over the details again.": "再仔细看一遍细节。",
    "Get off my foot.": "从我的脚上移开。",
    "I make an attempt.": "我尝试一下。",
    "The change had a good effect.": "这个改变有好效果。",
    "She sent him off to school.": "她送他去上学。",
    "She got through the test.": "她通过了考试。",
    "He makes the journey by train.": "他乘火车旅行。",
    "Come back to me.": "回到我身边。",
    "Do your work now.": "现在做你的工作。",
    "Go back to the start.": "回到起点。",
    "They have mixed feelings.": "他们有复杂的感觉。",
    "They sent the boy out.": "他们把男孩送走了。",
    "They made up after the fight.": "打完后他们和好了。",
    "Get over the wall.": "翻过墙。",
    "Come up and see the room.": "上来看看房间。",
    "Give me some help.": "给我一些帮助。",
    "He went through the book.": "他翻了那本书。",
    "She went over the work.": "她检查了工作。",
    "He did great harm.": "他造成了很大的伤害。",
    "I sent the letter off.": "我把信寄出去了。",
    "We do good work together.": "我们一起做很好的工作。",
    "We make decisions together.": "我们一起做决定。",
    "Go through the door.": "穿过门。",
    "I kept the baby in the room.": "我把婴儿留在房间里。",
    "She kept the light on.": "她让灯开着。",
    "I went over to see her.": "我走过去看她。",
    "They sent off the ship.": "他们派出了船。",
    "She made a request for help.": "她请求帮助。",
    "Go with me to the store.": "和我一起去商店。",
    "She kept out of the fight.": "她避开了打斗。",
    "I saw through his trick.": "我看穿了他的把戏。",
    "I do my work.": "我做我的工作。",
    "I got off the seat.": "我从座位上下来了。",
    "Get up the tree.": "爬到树上去。",
    "Do up your coat.": "把你的外套扣好。",
    "She gave support to the cause.": "她支持了这项事业。",
    "Keep your coat on.": "穿着你的外套。",
    "Go through the papers.": "翻阅文件。",
    "They went over the account.": "他们检查了账目。",
    "I give the answer.": "我给出答案。",
    "Do without food for a day.": "一天不吃东西。",
    "I give an offer of help.": "我提供帮助。",
    "He had a quick look.": "他快速看了一眼。",
    "They kept up the house.": "他们维护了房子。",
    "Give your orders now.": "现在给出你的命令。",
    "He gave out the money.": "他分发了钱。",
    "Give me back my pen.": "把我的笔还给我。",
    "The rain has an effect on the earth.": "雨对土地有影响。",
    "They gave us help.": "他们给了我们帮助。",
    "She let down her hair.": "她放下了头发。",
    "Give support when it is needed.": "在需要的时候给予帮助。",
    "Keep the dog out.": "把狗挡在外面。",
    "I have a belief in him.": "我对他有信心。",
    "He makes no attempt.": "他没有任何尝试。",
    "He made out a list.": "他列了一个清单。",
    "She made a start early.": "她早早开始了。",
    "She made an attempt to go.": "她试图去。",
    "We make comparisons all the time.": "我们一直在做比较。",
    "They went with the group.": "他们和团队一起走的。",
    "They went back together.": "他们一起回去了。",
    "He had no love for the work.": "他不喜欢这份工作。",
    "We do our writing at the office.": "我们在办公室写作。",
    "He did business with us.": "他和我们做生意。",
    "He did the work quickly.": "他很快做了工作。",
    "He saw to the business.": "他处理了事务。",
    "The price came down.": "价格下降了。",
    "I sent the letter back.": "我把信退回了。",
    "The book came out last year.": "这本书去年出版的。",
    "Send him back to his room.": "把他送回他的房间。",
    "They did the house over.": "他们翻新了房子。",
    "We made the change together.": "我们一起做了改变。",
    "She has a bad feeling.": "她有一种不好的感觉。",
    "Keep on working.": "继续工作。",
    "He let the room out.": "他把房间出租了。",
    "I came across an old friend.": "我偶遇了一个老朋友。",
    "Make a request in writing.": "以书面形式提出请求。",
    "I got back from the station.": "我从车站回来了。",
    "I do my reading at night.": "我晚上做阅读。",
    "The noise has an effect.": "噪音有影响。",
    "He let the water in.": "他让水进来了。",
    "She makes a move every time.": "她每次都采取行动。",
    "They sent back the goods.": "他们退回了货物。",
    "The train gets in at six.": "火车六点到站。",
    "She has love in her heart.": "她心中有爱。",
    "Give your full attention.": "全神贯注。",
    "Let the dog out.": "把狗放出去。",
    "He was let off lightly.": "他被从轻发落了。",
    "She gave attention to the details.": "她注意到了细节。",
    "Get up from the bed.": "从床上起来。",
    "I had a look at the book.": "我看了那本书。",
    "I will make a decision.": "我会做一个决定。",
    "Do it over again.": "再做一遍。",
    "We made use of the old building.": "我们利用了那栋旧楼。",
    "Do you make a decision?": "你做决定了吗？",
    "Have you a feeling about this?": "你对此有什么感觉吗？",
    "She kept on talking.": "她继续说着。",
    "I will do the writing.": "我来做写作。",
    "He gives no attention.": "他毫不在意。",
    "She gave a good offer.": "她给了一个好的提议。",
    "Have you a desire for more?": "你想要更多吗？",
    "I will make a journey soon.": "我很快就会去旅行。",
    "She made for home.": "她朝家走去。",
    "I keep on reading.": "我继续阅读。",
    "They have the same belief.": "他们有相同的信念。",
    "Come down to earth.": "回到现实。",
    "He was kept in after school.": "他放学后被留校了。",
    "I let my friend down.": "我让朋友失望了。",
    "I have little knowledge of it.": "我对此知之甚少。",
    "Give it a push.": "推它一下。",
    "They got up from the table.": "他们从桌子旁站起来了。",
    "They did all the work.": "他们做了所有的工作。",
    "He keeps on coming back.": "他不断回来。",
    "They kept on through the night.": "他们整夜继续着。",
    "Can you make out the picture?": "你能看清这幅画吗？",
    "I will make a change.": "我会做一个改变。",
    "Send off the parcel.": "寄出包裹。",
    "He got through the winter.": "他熬过了冬天。",
    "They got back together.": "他们又和好了。",
    "Give up the fight.": "放弃战斗。",
    "He makes a good comparison.": "他做了一个好的比较。",
    "I have a fear of falling.": "我害怕摔倒。",
    "See him off at the station.": "在车站送他。",
    "They went without water.": "他们没带水就去了。",
    "He got back his money.": "他拿回了他的钱。",
    "We did without a fire.": "我们没有火也能过。",
    "He had no knowledge of the plan.": "他不知道这个计划。",
    "We made an important discovery.": "我们做了一个重要的发现。",
    "She got over her fear.": "她克服了她的恐惧。",
    "She gave up the key.": "她交出了钥匙。",
    "Get back here soon.": "快点回来。",
    "Get back to the house.": "回到房子。",
    "They gave out the tickets.": "他们分发了票。",
    "I sent out the news.": "我发出了消息。",
    "I came down the steps.": "我走下了台阶。",
    "Give your offer in writing.": "以书面形式提供你的提议。",
    "Keep the fire down.": "把火关小。",
    "The sun came out.": "太阳出来了。",
    "I did harm to the plant.": "我伤害了植物。",
    "Send back the book.": "把书退回。",
    "She did up her hair.": "她整理了头发。",
    "She makes a decision.": "她做一个决定。",
    "Make use of what you have.": "利用你所拥有的。",
    "Make a move now.": "现在就行动。",
    "I gave in to her request.": "我屈服了她的请求。",
    "She made up her face.": "她化了妆。",
    "I make a journey every year.": "我每年旅行。",
    "I will do some reading.": "我会做一些阅读。",
    "She came across a new idea.": "她有了一个新想法。",
    "See me off at the door.": "在门口送我。",
    "He had no belief in the plan.": "他对这个计划没有信心。",
    "He gave back what he took.": "他归还了他拿走的东西。",
    "Let him off.": "放过他。",
    "I have a deep love for music.": "我热爱音乐。",
    "This color goes with that.": "这个颜色和那个相配。",
    "She came in quietly.": "她安静地进来了。",
    "She gave back the ring.": "她把戒指还了。",
    "She saw to the food.": "她处理了食物。",
    "They made for the sea.": "他们朝大海走去。",
    "He is getting on well.": "他进展得很好。",
    "We made the journey together.": "我们一起旅行。",
    "I make a change.": "我做一个改变。",
    "I had the tooth out.": "我拔了牙。",
    "He saw the work through.": "他看到了工作完成。",
    "She did without sleep.": "她不睡觉。",
    "I let the boy off.": "我放走了男孩。",
    "I could do with a drink.": "我需要喝点什么。",
    "She has on a new dress.": "她穿着一条新裙子。",
    "I came back from the station.": "我从车站回来了。",
    "He did without help.": "他没有帮助也做了。",
    "She got on with her work.": "她继续做她的工作。",
    "Have love for your country.": "热爱你的国家。",
    "Come back here.": "回到这里。",
    "She went through a hard time.": "她经历了一段艰难的时光。",
    "Do up the buttons.": "扣好扣子。",
    "Have a look at this.": "看看这个。",
    "See to the baby.": "照顾婴儿。",
    "He went over the wall.": "他翻过了墙。",
    "The boy made off with the cake.": "男孩带着蛋糕跑了。",
    "He gives a quick answer.": "他给出了一个快速的答案。",
    "I came up the street.": "我沿着街走上来了。",
    "She sent out for food.": "她派人去买食物了。",
    "How are you getting on?": "你怎么样了？",
    "He cannot keep up.": "他跟不上。",
    "She gave no answer.": "她没有给出答案。",
    "Give me an offer.": "给我一个提议。",
    "They got off the horse.": "他们下了马。",
    "I got in trouble.": "我遇到了麻烦。",
    "We give answers to all questions.": "我们回答所有问题。",
    "I came through the war.": "我经历了战争。",
    "He gives orders all day.": "他整天发号施令。",
    "She has red shoes on.": "她穿着红色的鞋。",
    "He came up with an idea.": "他想出了一个主意。",
    "He gives an offer every time.": "他每次都提供提议。",
    "I made a decision.": "我做了一个决定。",
    "Have the secret out.": "把秘密说出来。",
    "The machine gives off smoke.": "机器冒烟。",
    "They had the fight out.": "他们把架打完了。",
    "He will give in.": "他会屈服的。",
    "I sent off for the book.": "我订了那本书。",
    "Do your business quickly.": "快点做你的事。",
    "Go through the hole.": "穿过洞。",
    "He gave a hard push.": "他用力推了一下。",
    "I have a warm feeling.": "我有一种温暖的感觉。",
    "She got out at the station.": "她在车站下车了。",
    "Go without food for a day.": "一天不吃东西。",
    "They kept the water out.": "他们挡住了水。",
    "She came up to me.": "她走到我面前。",
    "She kept her feelings in.": "她隐藏了自己的感受。",
    "She made up the bed.": "她整理了床铺。",
    "I make a request.": "我提出一个请求。",
    "She made a long journey.": "她进行了一次长途旅行。",
    "He did the test over.": "他重新做了测试。",
    "He is doing the work.": "他正在做工作。",
    "They gave the cart a push.": "他们推了一下推车。",
    "I went through all my money.": "我花光了所有的钱。",
    "Get through the door.": "穿过门。",
    "I got on the seat.": "我坐在座位上。",
    "She has a desire for knowledge.": "她渴望知识。",
    "Have a look through the window.": "透过窗户看看。",
    "I made for the station.": "我朝车站走去。",
    "Give me an answer.": "给我一个答案。",
    "She kept the dog off.": "她把狗挡住了。",
    "The pain came back.": "疼痛又回来了。",
    "I let the cat in.": "我让猫进来了。",
    "She has no fear.": "她不害怕。",
    "I will give you an answer.": "我会给你一个答案。",
    "See through the window.": "透过窗户看。",
    "She got in through the window.": "她从窗户进来了。",
    "I make a decision.": "我做了一个决定。",
    "He came down from the tree.": "他从树上下来了。",
    "I have a feeling of joy.": "我有一种喜悦的感觉。",
    "Get the book back from her.": "从她那里把书拿回来。",
    "Have you knowledge of this?": "你了解这个吗？",
    "Get on the train.": "上火车。",
    "He sent out a call for help.": "他发出了求助信号。",
    "The wall gave in.": "墙塌了。",
    "She gave an answer.": "她给了答案。",
    "They got through the day.": "他们熬过了这一天。",
    "I kept the cold out.": "我把寒冷挡在外面。",
    "I went without sleep.": "我不睡觉。",
    "Come up to the window.": "走到窗户前。",
    "We do our reading together.": "我们一起做阅读。",
    "I gave the key back.": "我把钥匙还了。",
    "A question came up.": "出现了一个问题。",
    "I cannot get over this.": "我无法克服这个。",
    "I went through the room.": "我穿过了房间。",
    "He had on a hat.": "他戴着帽子。",
    "I give attention to the road.": "我注意道路。",
    "Make for the light.": "朝光亮的地方走去。",
    "He got over the shock.": "他克服了震惊。",
    "I make a discovery.": "我有一个发现。",
    "He makes a start every morning.": "他每天早上都开始。",
    "Get on with it.": "继续做。",
    "He did the writing for the group.": "他为团队写作。",
    "I kept my head down.": "我低着头。",
    "She has a great effect on him.": "她对他有很大影响。",
    "Come in and have a seat.": "进来坐。",
    "Have a look for yourself.": "你自己看看。",
    "She does good business.": "她生意做得好。",
    "Make out the words.": "辨认出词。",
    "See to the fire.": "照看火。",
    "She made good use of the time.": "她很好地利用了时间。",
    "Come up the steps.": "走上台阶。",
    "She came back soon.": "她很快就回来了。",
    "She does her work well.": "她工作做得好。",
    "He gives strong support.": "他给予强有力的支持。",
    "Get over here.": "过来。",
    "She came through the operation.": "她通过了手术。",
    "Let me off this time.": "这次放过我吧。",
    "The fire gives off heat.": "火散发热量。",
    "Give out the news.": "发布消息。",
    "She goes with him to work.": "她去和他一起工作。",
    "Have belief in yourself.": "相信自己。",
    "Go without your coat.": "不穿外套。",
    "They made a good attempt.": "他们做了一次好的尝试。",
    "She made a change to the plan.": "她对计划做了改变。",
    "I keep up with the news.": "我跟进新闻。",
    "Make a decision now.": "现在就做决定。",
    "They gave us their support.": "他们给予了我们支持。",
    "Go over your notes.": "复习你的笔记。",
    "He gives help freely.": "他免费帮助别人。",
    "She went without money.": "她没有带钱。",
    "She got back the ring.": "她拿回了戒指。",
    "Make a start now.": "现在就开始。",
    "She sent the food back.": "她退回了食物。",
    "I have no desire for that.": "我没有那个欲望。",
    "Make off with the money.": "带着钱跑掉。",
    "Keep on with your work.": "继续你的工作。",
    "She let in the light.": "她让光线进来。",
    "He came in late.": "他迟到了。",
    "Let some air in.": "让一些空气进来。",
    "Give an answer by tomorrow.": "明天之前给出答案。",
    "Give help when you can.": "在你能够帮助的时候提供帮助。",
    "Give your support to the plan.": "支持这个计划。",
    "I give support to my friend.": "我支持我的朋友。",
    "Have them in for a meal.": "请他们来家里吃饭。",
    "We made a good start.": "我们开了个好头。",
    "I saw my friend off.": "我送别了我的朋友。",
    "I have a desire for food.": "我有食欲。",
    "I make a comparison.": "我做了一个比较。",
    "I give help to my friend.": "我帮助我的朋友。",
    "I will make a discovery one day.": "我总有一天会有一个发现。",
    "They have fears about the future.": "他们对未来感到恐惧。",
    "I went with a friend.": "我和朋友一起去了。",
    "She gave up her seat.": "她让出了座位。",
    "I will make a request.": "我会提出一个请求。",
    "They gave up the town.": "他们放弃了城镇。",
    "I gave him a push.": "我推了他一下。",
    "Come through the town.": "穿过城镇。",
    "They came back together.": "他们一起回来了。",
    "Get through the work.": "完成工作。",
    "She gave the order to go.": "她下命令离开。",
    "The meat gives off a bad smell.": "肉散发出难闻的气味。",
    "I came across the book in the store.": "我在商店里偶然发现了那本书。",
    "Come out and play.": "出来玩。",
    "He kept out of trouble.": "他避开了麻烦。",
    "Give the door a push.": "推一下门。",
    "What do you have on?": "你穿了什么？",
    "He made the first move.": "他先行动了。",
    "I let out a cry.": "我发出了一声叫喊。",
}

# 读取数据并更新
data_path = "/Users/cuijianchen/Projects/OgdenBasicEnglish/data/training-core.jsonl"
sentences = []
with open(data_path, "r") as f:
    for line in f:
        if line.strip():
            sentences.append(json.loads(line.strip()))

# 更新 Step 1+2 的中文
updated = 0
for s in sentences:
    if s.get("step") in [1, 2] and s["sentence"] in ZH_462:
        old_zh = s.get("zh", "")
        if re.match(r'^[a-z]+\+[a-z]+', old_zh):
            s["zh"] = ZH_462[s["sentence"]]
            updated += 1

print(f"Updated {updated} translations")

# 写文件
with open(data_path, "w") as f:
    for s in sentences:
        f.write(json.dumps(s, ensure_ascii=False) + "\n")
print(f"Written to {data_path}")

# 验证
still_pattern = sum(1 for s in sentences if s.get("step") in [1,2] and re.match(r'^[a-z]+\+[a-z]+', s.get("zh","")))
print(f"Still pattern-based zh: {still_pattern}")

# 推 GitHub
import subprocess
subprocess.run(["git", "add", "data/training-core.jsonl"], cwd="/Users/cuijianchen/Projects/OgdenBasicEnglish")
subprocess.run(["git", "commit", "-m", "data: update zh translations for Step 1+2 (462 sentences, human-readable)"], cwd="/Users/cuijianchen/Projects/OgdenBasicEnglish")
result = subprocess.run(["git", "push", "origin", "main"], cwd="/Users/cuijianchen/Projects/OgdenBasicEnglish", capture_output=True, text=True)
print(f"Git push: {result.stdout[-200:] if result.stdout else ''}")
print(f"Git push stderr: {result.stderr[-200:] if result.stderr else ''}")
